# Generated by Django 4.0.4 on 2022-05-27 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 30, 42, 613788)),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isFollowing', to=settings.AUTH_USER_MODEL)),
                ('userFollowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isFollowed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
